### ISSUE TITLE
Using your utility out of MUL-T's alternate special breaks autosprint.

### ISSUE THREAD

**Issue by APPARENTLY-OK** [JohnEdwa/RTAutoSprintExtended#10]
This issue can be fixed by recasting duel wield to cancel the ability, however shifting whilst it is active will break it until you do this.

**Comment by JohnEdwa** [comment]
I just pushed out an update that should fix this and the issue of MUL-T dropping out of the dual wield mode.

**Comment by APPARENTLY-OK** [comment]
This was with the latest patch.

**Comment by APPARENTLY-OK** [comment]
This issue comes from shifting whilst duel wield is active, it will break autosprint for MUL-T until he uses his special again, then cancels it by reactivating the special.

**Comment by APPARENTLY-OK** [comment]
It's pretty hard to explain in text so heres a little video that covers the issue I had
https://www.youtube.com/watch?v=IWoO3dtICOs

**Comment by APPARENTLY-OK** [comment]
Turns out thunderstore wasn't fully updated on my R2modman, this is not an issue anymore.

**Comment by JohnEdwa** [comment]
Hmh, I can't reproduce that.
If you use R2modman, could you go to Settings -> Profile -> Export Profile As A Code and post it here? It has to be some mod incompatibility issue.

**Comment by JohnEdwa** [comment]
Ah, that would explain it.   

But your video did show something else, mainly that you don't have the EnigmaticThunder debug info on your main screen which made me realize that if you enable R2API and EnigmaticThunder at the same time they conflict and break eachother. So if you have any further issues, with any mod, not just mine, try disabling one or the other first.
