### ISSUE TITLE
R2API ContentPack issues v.1.1.1.2

### ISSUE THREAD

**Issue by Webrow** [JohnEdwa/RTAutoSprintExtended#12]
Hey JohnEdwa, 
Since today (updated R2API and ROR2) 

[Info   :   BepInEx] Loading [RTAutoSprintEx 1.3.2]
[Error  : Unity Log] InvalidOperationException: CommandHelper is not loaded. Please use [R2APISubmoduleDependency(nameof(CommandHelper)]
Stack trace:
R2API.Utils.CommandHelper.AddToConsoleWhenReady () (at <1bd6ab2074854c4394e063180e61f262>:0)
RTAutoSprintEx.RTAutoSprintEx.Awake () (at <a8fd7a0263954f19b37b47dc8749c991>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

Ill also be crossposting to R2API,  I assume you need the contentpack that is errored. 
[Info   :   BepInEx] Loading [R2API 3.0.11]
[Error  : Unity Log] TypeLoadException: Could not load type of field 'R2API.R2APIContentPackProvider:ContentPack' (0) due to: Could not resolve type with token 01000020 (from typeref, class/assembly RoR2.ContentPack, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:RoR2.ContentPack member:(null) signature:<none>
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by JohnEdwa** [comment]
The update broke R2API, as they always do.
