### ISSUE TITLE
Unable to be used with FOV mod

### ISSUE THREAD

**Issue by Kommynct** [JohnEdwa/RTAutoSprintExtended#15]
https://github.com/KosmosisDire/ChangeFOVSettings/issues/1

I'd really love to be able to use these mods together, dunno what could be conflicting.

**Comment by Kommynct** [comment]
Ugh i'm stupid I didn't see that this mod had FOV settings, I do think this should be compartmentalized into the other mod though, less code for you, and a little bit more logical.

**Comment by JohnEdwa** [comment]
The reason they are included is because of the sprinting FOV change, it's been there for almost two years now.

Setting them both to 0 in the config should work to disable the code changes.
