### ISSUE TITLE
client only?

### ISSUE THREAD

**Issue by DAmNRelentless** [JohnEdwa/RTAutoSprintExtended#18]
Is this a client only mod?
And if not, what happens if the host has it installed but the other players do not?

**Comment by JohnEdwa** [comment]
Yes. Essentially all it does is automatically press the sprint button, and the rest of the code is bunch of conditions when it shouldn't. Plus a few UI tweaks.

**Comment by DAmNRelentless** [comment]
I just gave it a go and I am in love with this mod. Awesome work! I hate that RoR2 only has a toggle option for the sprint and your mod is a live-saver.
In the mod manager, I saw that you listed it as a client-side mod but I wasn't able to find it on the hosting site, that's why I asked. Thanks for the response!
