### ISSUE TITLE
IL hook conflict with Rogue Wisp

### ISSUE THREAD

**Issue by Reinms** [JohnEdwa/RTAutoSprintExtended#2]
Rogue Wisp and RTAutoSprint are both IL hooking the same conditional in CrosshairManager.UpdateCrosshair.

Rather than replacing the isSprinting call with a false, could you instead emit it as false or isSprinting?
Example:
```
c.GotoNext( MoveType.After, x => x.MatchCallOrCallVirt<RoR2.CharacterBody>("get_isSprinting"));
c.Emit( OpCodes.Ldc_I4, 0 );
c.Emit( OpCodes.Or );
```
May be a typo there as I am on mobile.

That should resolve the issue, but I may also need to alter my code to operate similarly to prevent the issue. If so I will update later today.

For reference, this is the structure of the IL hook I am using in the same area (off of memory atm, but should be correct):

```
c.GotoNext(MoveType.Before, x=> x.MatchCallOrCallVirt<RoR2.CharacterBody>( "get_isSprinting" ));
c.Remove();
c.EmitDelegate<Func<RoR2.CharacterBody,Boolean>>( (body) => body.isSprinting && !this.HashSet.Contains( body ));
```

Edit: grabbed code from repo with what I will be updating to in a few hours
```
            c.GotoNext( MoveType.After, x => x.MatchCallvirt<RoR2.CharacterBody>( "get_isSprinting" ) );
            c.Emit( OpCodes.Ldarg_1 );
            c.EmitDelegate<Func<CharacterBody, Boolean>>( ( body ) => !this.RW_BlockSprintCrosshair.Contains( body ) );
            c.Emit( OpCodes.And );
```

**Comment by JohnEdwa** [comment]
Hummh, if I change to be "isSprinting and false", would it work on your side?

```
IL.RoR2.UI.CrosshairManager.UpdateCrosshair += (il) => {
    ILCursor c = new ILCursor(il);
    c.GotoNext( 
		MoveType.After, 
		x => x.MatchLdarg(1), 
		x => x.MatchCallvirt<CharacterBody>("get_isSprinting")
	);
	c.Emit(OpCodes.Ldc_I4, 0);
	c.Emit(OpCodes.And);
};	
```

I can't make it "isSprinting or false" as that would still return true when you sprint and it wouldn't actually remove the crosshair.

**Comment by ReinMasamune** [comment]
Yeah I meant to say and, my bad.

**Comment by JohnEdwa** [comment]
Made the change and [published an RC on Github](https://github.com/JohnEdwa/RTAutoSprintExtended/releases/tag/1.0.4-RC1), could you test it will work properly?

**Comment by ReinMasamune** [comment]
Yep that seems to have fixed it, thanks a ton.
