### ISSUE TITLE
Where do we set configurations?

### ISSUE THREAD

**Issue by ruchibuchi** [JohnEdwa/RTAutoSprintExtended#20]
In the ReadMe you mentioned config settings such as HoldSprintToWalk and DisabledAutoSprinting.  Where exactly are these configurations set?  Which file do we go to?  I see no .cfg file included in this plugin.

**Comment by JohnEdwa** [comment]
Like every other bepinex plugin, it's generated when you launch the game with a mod enabled and can then be found in the bepinex folder, or it can be edited directly from r2modmanager.
