### ISSUE TITLE
Please update for new version :D

### ISSUE THREAD

**Issue by RandomNerd1** [JohnEdwa/RTAutoSprintExtended#8]
This mod saves me a lot of finger cramping, lol

**Comment by MoonSha** [comment]
Eager to play the new hero but not without auto sprint, should have been included in the patch!

**Comment by brandonvdongen** [comment]
Got so used to having this that I completely forgot I had it in the first place and now I keep forgetting to sprint and constantly go down as a result.

**Comment by DestroyTargetNonBasicLand** [comment]
The game is literally unplayable for me without this mod.. I hope it gets updated fast.

**Comment by joaomiguelrcf** [comment]
Please do update it for the new patch. I've used dozens of mods in my game and I must say this is the single best QoL mod out there. Makes the game SO much better that I literally cannot go back to vanilla

**Comment by JohnEdwa** [comment]
Updating the mod requires either R2API to be updated first or porting it to EnigmaticThunder which I'm not quite sure how. Seeing as the R2API update might take a while I'll give that a go though.

**Comment by JohnEdwa** [comment]
This one should fix the MUL-T Dual Wielding sometimes getting randomly cancelled. Hopefully.

[1_2_0_Beta2.zip](https://github.com/JohnEdwa/RTAutoSprintExtended/files/6233161/1_2_0_Beta2.zip)

**Comment by JohnEdwa** [comment]
I pushed the update to Thunderstore, if anyone finds anything that isn't working, do tell me, it's impossible for me to test everything.
