### ISSUE TITLE
MUL-T's alternate special sporadically cancels autosprint

### ISSUE THREAD

**Issue by APPARENTLY-OK** [JohnEdwa/RTAutoSprintExtended#9]
I've noticed this issue most frequently jumping with autosprint and moving forwards simulataneously.
I had this issue with double scrap launcher.

**Comment by JohnEdwa** [comment]
Goddamnit, I thought I managed to fix that. The only thing that should be capable of reactivating autosprint while in the dual wield mode is actually exiting that mode.    
Something weird is going on with that mode, I'll take a look at it.

**Comment by APPARENTLY-OK** [comment]
Not an issue anymore fixed with the latest patch
